### ISSUE TITLE
Can we use this in iOS also ?

### ISSUE THREAD

**Issue by dhaneshgosai** [Henryforce/KRActivityIndicatorView#1]
Hello,

How can we use this Activity Indicator in iOS apps ?

Thanks,
Dhanesh gosai.

**Comment by Henryforce** [comment]
Howdy Dhanesh!
Unfortunately, this repository only works for OSX. But you can use the following repository for iOS (from which the code is actually based):
https://github.com/ninjaprox/NVActivityIndicatorView
Best regards,
Henry

**Comment by dhaneshgosai** [comment]
Hey Henryforce,

Thanks dear for your quick reply.

Let me check this repo.

Thanks,
Dhanesh
